#!/bin/bash

REMOTE_ORACLE_LOG_USER=nexthink
REMOTE_ORACLE_LOG_SERVER=sfpld19901.ad.sys
REMOTE_ORACLE_LOG_DIR_IN=/volume1/oracle_log/check/ok
REMOTE_ORACLE_LOG_DIR_DONE=/volume1/oracle_log/done

LOCAL_ORACLE_LOG_DIR_IN=/datalab3/DATA/ORACLE/in
LOCAL_ORACLE_LOG_DIR_DONE=/datalab3/DATA/ORACLE/done && [[ -f $LOCAL_ORACLE_LOG_DIR_DONE ]] || mkdir -p $LOCAL_ORACLE_LOG_DIR_DONE
LOCAL_ORACLE_LOG_DIR_ENCODED=/datalab3/DATA/ORACLE/encoded && [[ -f $LOCAL_ORACLE_LOG_DIR_ENCODED ]] || mkdir -p $LOCAL_ORACLE_LOG_DIR_ENCODED
LOCAL_ORACLE_LOG_DIR_SENT=/datalab3/DATA/ORACLE/sent2s3 && [[ -f $LOCAL_ORACLE_LOG_DIR_SENT ]] || mkdir -p $LOCAL_ORACLE_LOG_DIR_SENT
LOCAL_ORACLE_LOG_DIR_TRASH=/datalab3/DATA/ORACLE/trash && [[ -f $LOCAL_ORACLE_LOG_DIR_TRASH ]] || mkdir -p $LOCAL_ORACLE_LOG_DIR_TRASH
