#!/bin/bash

REMOTE_ORACLE_LOG_USER=nexthink
REMOTE_ORACLE_LOG_SERVER=sfpld19901.ad.sys
REMOTE_ORACLE_LOG_DIR_IN=/volume1/oracle_log/v2/in
REMOTE_ORACLE_LOG_DIR_DONE=/volume1/oracle_log/v2/done

LOCAL_ORACLE_LOG_DIR_IN=/datalab3/DATA/ORACLE/0-in
LOCAL_ORACLE_LOG_DIR_DONE=/datalab3/DATA/ORACLE/0-done && [[ -f $LOCAL_ORACLE_LOG_DIR_DONE ]] || mkdir -p $LOCAL_ORACLE_LOG_DIR_DONE
LOCAL_ORACLE_LOG_DIR_ENCODED=/datalab3/DATA/ORACLE/1-encoded && [[ -f $LOCAL_ORACLE_LOG_DIR_ENCODED ]] || mkdir -p $LOCAL_ORACLE_LOG_DIR_ENCODED
LOCAL_ORACLE_LOG_DIR_TRASH=/datalab3/DATA/ORACLE/1-trash && [[ -f $LOCAL_ORACLE_LOG_DIR_TRASH ]] || mkdir -p $LOCAL_ORACLE_LOG_DIR_TRASH
LOCAL_ORACLE_LOG_DIR_REPORT=/datalab3/DATA/ORACLE/1-report && [[ -f $LOCAL_ORACLE_LOG_DIR_REPORT ]] || mkdir -p $LOCAL_ORACLE_LOG_DIR_REPORT
DIRLOG=/datalab3/DATA/ORACLE/log && [[ -f $DIRLOG ]] || mkdir -p $DIRLOG
