<<<

== Server usage

Another data sources that we collect to analyse is _Server Usage_.
It involves the information about server CPU usage, memory and storage usage.

* Source code path : ALDataLab/collect/serverconsumption.



=== Method

In order to collect a server's usage information we need to request
an HTTP URL by specifying its hostname as a parameter.
This URL and other configuration parameters are defined in conf.sh file as below.

[source,bash]
.collect/serverconsumption/conf/conf.sh
----
include::../collect/serverconsumption/conf/conf.sh[lines=4..5]
----


=== List of servers

List of servers are defined in _server.lst_ file.
Each line represents a hostname of a server.
They are used by collect script.

[source,markdown]
.collect/serverconsumption/conf/server.lst
----
include::../collect/serverconsumption/conf/server.lst[lines=1..5]
...
----


=== Collect

As we know how to fetch _Server usage_ for a single one, we can handle this for all others too.
Request answer for each server is a XLS file.
Later, we will convert these files into CSV formats.

[source,bash]
.collect/serverconsumption/bin/collect.sh
----
include::../collect/serverconsumption/bin/collect.sh[lines=16..22]
----


=== Convert XLS to CSV

Once we collected all XLS files we convert them to CSV format.
Finally, we compress them into .gz zip format.

[source,bash]
.collect/serverconsumption/bin/convert-send.sh
----
include::../collect/serverconsumption/bin/convert-send.sh[lines=10..20]
----


IMPORTANT: There is nothing to make anonymous for these kind of data collection.

NOTE: Server-usage data are synchronized 2 times in a week.


